name: gameball_sdk
description: "Gameball Integration SDK allowing direct communication with multiple Gameball services like Customer creation, sending Events, and showing Gameball Profile"
version: 1.0.0
homepage: https://gameball.co
repository: https://github.com/gameballers/gameball-flutter

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_dynamic_links: ^6.0.4
  firebase_messaging: ^15.0.4

  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  package_info_plus: ^8.0.2

  platform_info: ^4.0.2 
  webview_flutter: ^3.0.4
  build_runner: ^2.4.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0